In [1]:
import numpy as np 
import pandas as pd

In [2]:
df=pd.read_csv('zepto_mess.csv')

In [3]:
df

,Order_ID,Delivery_Time,Order_Value,Items_Count,Distance_km,Delivery_Charge,Surge_Pricing,Time_Slot,Warehouse_Location,Rider_Rating,Customer_Rating,Inventory_Issue,Payment_Method,Order_Status
0,1,43.0,1408,14.0,8.0,103.0,0.0,Morning,Central Hub,7.0,2.0,Unknown,Unknown,Unknown
1,2,56.0,908,10.0,14.0,67.0,0.0,Afternoon,??,NaN,4.0,NaN,Card,Unknown
2,3,33.0,484,11.0,-3.0,94.0,0.0,Afternoon,Unknown,5.0,4.0,Unknown,UPI,Delivered
3,4,19.0,496,2.0,12.0,64.0,1.0,Morning,South Hub,4.0,4.0,Yes,Crypto?,Cancelled
4,5,47.0,1381,9.0,14.0,48.0,NaN,Afternoon,South Hub,7.0,NaN,No,Card,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,42.0,1648,15.0,10.0,38.0,0.0,??,East Hub,7.0,10.0,No,Crypto?,Delivered
996,997,54.0,1383,17.0,10.0,88.0,2.0,Afternoon,??,3.0,8.0,Unknown,Unknown,Cancelled
997,998,38.0,934,8.0,13.0,61.0,1.0,Afternoon,West Hub,5.0,4.0,Yes,Unknown,Delivered
998,999,22.0,1316,18.0,11.0,140.0,NaN,Afternoon,Unknown,5.0,1.0,Yes,Card,Delivered
999,1000,34.0,1566,9.0,13.0,108.0,NaN,Late Night,East Hub,2.0,10.0,No,Crypto?,Cancelled

In [4]:
df.isnull().sum()

Order_ID                0
Delivery_Time          10
Order_Value             0
Items_Count            44
Distance_km            60
Delivery_Charge         5
Surge_Pricing         255
Time_Slot             168
Warehouse_Location    121
Rider_Rating          112
Customer_Rating       117
Inventory_Issue       245
Payment_Method        153
Order_Status            0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            1000 non-null   int64
 1   Delivery_Time       990 non-null    float64
 2   Order_Value         1000 non-null   int64
 3   Items_Count         956 non-null    float64
 4   Distance_km         940 non-null    float64
 5   Delivery_Charge     995 non-null    float64
 6   Surge_Pricing       745 non-null    float64
 7   Time_Slot           832 non-null    object
 8   Warehouse_Location  879 non-null    object
 9   Rider_Rating        888 non-null    float64
 10  Customer_Rating     883 non-null    float64
 11  Inventory_Issue     755 non-null    object
 12  Payment_Method      847 non-null    object
 13  Order_Status        1000 non-null   object
dtypes: float64(7), int64(2), object(5)
memory usage: 109.5+ KB

In [6]:
df.describe()

,Order_ID,Delivery_Time,Order_Value,Items_Count,Distance_km,Delivery_Charge,Surge_Pricing,Rider_Rating,Customer_Rating
count,1000.000000,990.000000,1000.000000,956.000000,940.000000,995.000000,745.000000,888.000000,883.000000
mean,500.500000,32.688889,1012.156000,9.084728,9.684043,76.091457,1.022819,3.725225,3.835787
std,288.819436,20.192906,568.829821,6.224940,11.996590,42.467323,0.815353,3.117206,3.664995
min,1.000000,-10.000000,50.000000,-5.000000,-3.000000,-20.000000,0.000000,-1.000000,-2.000000
25%,250.750000,18.000000,537.000000,4.000000,3.000000,42.000000,0.000000,2.000000,1.000000
50%,500.500000,32.000000,1010.000000,9.000000,7.000000,76.000000,1.000000,3.000000,3.000000
75%,750.250000,46.000000,1497.500000,14.000000,12.000000,112.000000,2.000000,5.000000,8.000000
max,1000.000000,120.000000,1996.000000,19.000000,50.000000,149.000000,2.000000,10.000000,10.000000

In [7]:
# Items count should be positive

df = df[df['Items_Count'] > 0]

In [8]:
# Distance should be realistic (0–20 km)

df = df[(df['Distance_km'] > 0) & (df['Distance_km'] < 20)]

In [9]:
# Delivery time realistic (0–60 mins)

df = df[(df['Delivery_Time'] > 0) & (df['Delivery_Time'] < 60)]

In [10]:
# Delivery charge >= 0

df = df[df['Delivery_Charge'] >= 0]

In [11]:
df.isnull().sum()

Order_ID                0
Delivery_Time           0
Order_Value             0
Items_Count             0
Distance_km             0
Delivery_Charge         0
Surge_Pricing         174
Time_Slot             108
Warehouse_Location     86
Rider_Rating           84
Customer_Rating        85
Inventory_Issue       160
Payment_Method         93
Order_Status            0
dtype: int64

In [12]:
df = df[(df['Customer_Rating'].between(1,5)) & 
        (df['Rider_Rating'].between(1,5))]

In [13]:
df['Surge_Pricing'] = df['Surge_Pricing'].apply(lambda x: 1 if x==1 else 0)

In [14]:
df.replace(['??','Unknown','Crypto?'], np.nan, inplace=True)

In [15]:
# num_cols = [
#     'Delivery_Time',
#     'Order_Value',
#     'Items_Count',
#     'Distance_km',
#     'Delivery_Charge',
#     'Rider_Rating',
#     'Customer_Rating'
# ]

# for i in num_cols:
#     df[i].fillna(df[i].median(), inplace=True)

In [18]:
cat_cols = [
    'Time_Slot',
    'Warehouse_Location',
    'Payment_Method',
    'Inventory_Issue',
    'Order_Status'
]

for i in cat_cols:
    df[i].fillna(df[i].mode()[0], inplace=True)

In [19]:
df.isnull().sum()

Order_ID              0
Delivery_Time         0
Order_Value           0
Items_Count           0
Distance_km           0
Delivery_Charge       0
Surge_Pricing         0
Time_Slot             0
Warehouse_Location    0
Rider_Rating          0
Customer_Rating       0
Inventory_Issue       0
Payment_Method        0
Order_Status          0
dtype: int64

In [20]:
df.duplicated().any()

np.False_

In [21]:
df['Delivery_Efficiency'] = df['Distance_km'] / df['Delivery_Time']

In [22]:
df.head()

,Order_ID,Delivery_Time,Order_Value,Items_Count,Distance_km,Delivery_Charge,Surge_Pricing,Time_Slot,Warehouse_Location,Rider_Rating,Customer_Rating,Inventory_Issue,Payment_Method,Order_Status,Delivery_Efficiency
3,4,19.0,496,2.0,12.0,64.0,1,Morning,South Hub,4.0,4.0,Yes,UPI,Cancelled,0.631579
10,11,27.0,1069,15.0,9.0,113.0,0,Afternoon,North Hub,3.0,2.0,Yes,UPI,Delivered,0.333333
13,14,28.0,1179,3.0,13.0,51.0,0,Late Night,North Hub,4.0,2.0,No,UPI,Delivered,0.464286
15,16,40.0,130,17.0,14.0,53.0,0,Afternoon,South Hub,4.0,2.0,No,Card,Delivered,0.350000
19,20,26.0,187,18.0,12.0,20.0,0,Late Night,South Hub,5.0,3.0,Yes,UPI,Delivered,0.461538

In [23]:
df['Avg_Order_Value'] = df['Order_Value'] / df['Items_Count']

In [24]:
df['Late_Delivery'] = (df['Delivery_Time'] > 20).astype(int)

In [25]:
# df['CX_Score'] = (df['Customer_Rating'] + df['Rider_Rating']) / 2

In [26]:
df['Cancelled'] = (df['Order_Status'] == 'Cancelled').astype(int)

In [27]:
df['Net_Revenue'] = df['Order_Value'] - df['Delivery_Charge']

In [28]:
df['Order_Size'] = pd.cut(df['Order_Value'], 3, labels=['Low','Medium','High'])

In [29]:
df['Distance_Category'] = pd.cut(df['Distance_km'],
                                bins=[0,5,10,20],
                                labels=['Near','Medium','Far'])

In [30]:
df.head()

,Order_ID,Delivery_Time,Order_Value,Items_Count,Distance_km,Delivery_Charge,Surge_Pricing,Time_Slot,Warehouse_Location,Rider_Rating,...,Inventory_Issue,Payment_Method,Order_Status,Delivery_Efficiency,Avg_Order_Value,Late_Delivery,Cancelled,Net_Revenue,Order_Size,Distance_Category
3,4,19.0,496,2.0,12.0,64.0,1,Morning,South Hub,4.0,...,Yes,UPI,Cancelled,0.631579,248.000000,0,1,432.0,Low,Far
10,11,27.0,1069,15.0,9.0,113.0,0,Afternoon,North Hub,3.0,...,Yes,UPI,Delivered,0.333333,71.266667,1,0,956.0,Medium,Medium
13,14,28.0,1179,3.0,13.0,51.0,0,Late Night,North Hub,4.0,...,No,UPI,Delivered,0.464286,393.000000,1,0,1128.0,Medium,Far
15,16,40.0,130,17.0,14.0,53.0,0,Afternoon,South Hub,4.0,...,No,Card,Delivered,0.350000,7.647059,1,0,77.0,Low,Far
19,20,26.0,187,18.0,12.0,20.0,0,Late Night,South Hub,5.0,...,Yes,UPI,Delivered,0.461538,10.388889,1,0,167.0,Low,Far

In [37]:
df.to_csv("zepto_cleaned.csv", index=False)

In [32]:


# # Items_Count: should be > 0
# df.loc[df['Items_Count'] <= 0, 'Items_Count'] = np.nan

# # Distance: should be between 1–20
# df.loc[(df['Distance_km'] <= 0) | (df['Distance_km'] > 20), 'Distance_km'] = np.nan

# # Delivery Time: should be between 5–60
# df.loc[(df['Delivery_Time'] <= 0) | (df['Delivery_Time'] > 60), 'Delivery_Time'] = np.nan

# # Delivery Charge: should be >= 0
# df.loc[df['Delivery_Charge'] < 0, 'Delivery_Charge'] = np.nan

In [33]:
df['Surge_Pricing']

3      1
10     0
13     0
15     0
19     0
      ..
981    1
986    0
991    1
997    1
998    0
Name: Surge_Pricing, Length: 204, dtype: int64

In [34]:
df.describe()

,Order_ID,Delivery_Time,Order_Value,Items_Count,Distance_km,Delivery_Charge,Surge_Pricing,Rider_Rating,Customer_Rating,Delivery_Efficiency,Avg_Order_Value,Late_Delivery,Cancelled,Net_Revenue
count,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000
mean,494.661765,31.754902,951.093137,9.480392,7.838235,77.848039,0.230392,3.044118,2.813725,0.373923,199.996381,0.720588,0.254902,873.245098
std,289.170886,15.170906,569.908511,5.427045,3.998560,40.248140,0.422120,1.390685,1.387704,0.420371,305.900399,0.449814,0.436878,567.035406
min,4.000000,5.000000,53.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.018519,3.647059,0.000000,0.000000,-54.000000
25%,263.750000,19.000000,412.000000,5.000000,4.000000,47.000000,0.000000,2.000000,2.000000,0.132051,46.311842,0.000000,0.000000,333.750000
50%,490.000000,32.000000,976.000000,9.000000,8.000000,74.000000,0.000000,3.000000,3.000000,0.263605,103.041667,1.000000,0.000000,888.500000
75%,756.250000,43.000000,1379.000000,14.000000,12.000000,111.250000,0.000000,4.000000,4.000000,0.407629,208.466667,1.000000,1.000000,1312.250000
max,999.000000,58.000000,1995.000000,19.000000,14.000000,149.000000,1.000000,5.000000,5.000000,2.600000,1878.000000,1.000000,1.000000,1913.000000

In [35]:
df['Rider_Rating'].mean()

np.float64(3.0441176470588234)

In [36]:
df['Customer_Rating'].mean()

np.float64(2.8137254901960786)